/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jenkins_java_lib;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Hello multibranching!");
        return true;
    }
}
